git_rm $(find libs/rs -name Android.mk)
git_rm $(find graphics/jni -name Android.mk)
git_rm $(find graphics/tests -name Android.mk)
git_rm $(find core/tests -name Android.mk)
git_rm $(find packages -name Android.mk)
